version: '3'

services:

  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    command: --init-file /data/application/init.sql
    volumes:
      - app-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=root

  app:
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    depends_on:
      - db
    command: sh -c "/wait && uvicorn nft_service.src.main:app --reload --host 0.0.0.0 --port 5000"
    env_file:
      - .env
    environment:
      - WAIT_HOSTS=db:3306
    links:
      - db

volumes:
  app-data:
